### ISSUE TITLE
Getting error messages or logging errors in the Swiftmailer extension.

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2-swiftmailer#4]
Swiftmailer send function returns false. But there are no error messages in any logs or object properties I can find. Swiftmailer docs say there is a logger plugin to do logging for Swiftmailer but I have no idea how to configure it with Yii configs. How do I get any status info or error messages out of swiftmailer in Yii? The guide and the docs say nothing regarding the error handling at all.

Migrated from https://github.com/yiisoft/yii2/issues/7524

**Comment by klimov-paul** [comment]
Resolved by commit d30d730

**Comment by francislavoie** [comment]
@klimov-paul this is still missing documentation... I had to find this information via git commits/issues. :/

**Comment by klimov-paul** [comment]
There is doc comment for it:
https://github.com/yiisoft/yii2-swiftmailer/blob/master/Mailer.php#L82-L87

As you can see this repository does not have any specific documentation (`docs` folder). If you are readys to compose it - be my guest - open a PR for it.

**Comment by francislavoie** [comment]
I meant it's not in this documentation: http://www.yiiframework.com/doc-2.0/guide-tutorial-mailing.html
That guide should document every available option.

**Comment by klimov-paul** [comment]
No, this guide describes universal settings amoung all possible mailers.
Swift logger option does not belong to them. For example: solution based on Zend Email will not have it.

**Comment by francislavoie** [comment]
Then the README for this repo shouldn't link to that page.

`For further instructions refer to the [related section in the Yii Definitive Guide](http://www.yiiframework.com/doc-2.0/guide-tutorial-mailing.html).`

**Comment by klimov-paul** [comment]
Why? You think the documentation linked does describe mailing processes and contain something, which is not true in the scope of `yii2-swiftmailer`?

As I said, if you have will and spare time to write the docs specific to this repo - feel free to start.
We do not have resources we can spare for creating a docs for single property.
