### ISSUE TITLE
Does yii/swiftmailer able to add custom mail header?

### ISSUE THREAD

**Issue by chaintan17** [yiisoft/yii2-swiftmailer#6]
I have use mandrill as my smtp server.
And they work great.
One feature that i want to use in my site is the mail tagging feature.
It will help me to read the report easier.

However, to tag mail, they need to add custom header while sending mail.

I was wondering, is yii/swiftmail is able to do this?

Please kindly advise.

Thank you.

**Comment by klimov-paul** [comment]
You can always get to the Swift Message instance for this purpose:
```php
$message = Yii::$app->mailer->compose(...);
$message->getSwiftMessage()->getHeaders()->addTextHeader('name', 'value');
```
Although perhaps base `yii\mail\MessageInterface` should be adjusted to provide headers control.

**Comment by yurii-github** [comment]
i did as

//controller
		\Yii::$app->mailer->compose(['html'=> 'newsletter/html'], ['heads'=>$heads])
			->setFrom($from)
			->setTo($to)
			->setSubject($subject)
			->send();

//view
/* @var $sm Swift_Message */
$sm = $message->getSwiftMessage();
foreach ($heads as $n => $v) {
	$sm->getHeaders()->addTextHeader($n, $v);
}


also, it looks like documentation does not make real note that parameter 'message' is set during view render and can be overriden by acident. (i say about function compose() ). only when embeding image https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-mailing.md

**Comment by zharnikov** [comment]
This solution breaks encapsulation

**Comment by klimov-paul** [comment]
Resolved by commit f18745f052e3c235acd47519b1664a5e1cfd5f1d

**Comment by alexander-ronin** [comment]
I don't figure out, so how can I add entry in the header? In 2 years info about this still does not added to official documentation... Madness!
